### ISSUE TITLE
View

### ISSUE THREAD

**Issue by NeilMD** [AhmedAli7O1/hapi-arch#8]
This is more like a concern than a problem. I'm wondering why view isnt included in the framework

**Comment by AhmedAli7O1** [comment]
well, it's more like an independent API, primarily I build it for my projects which is a micro-services based architecture, so it has nothing to do with any view engine or server side rendering.
however I'm planing to add more support out of the box, e.g web sockets, view engines, docker and docker-swarm, testing framework, and many other stuff.

**Comment by NeilMD** [comment]
Thank you! Hope you continue working in this 👍
